import argparse
import sys

from pyramid.paster import bootstrap, setup_logging
from sqlalchemy.exc import OperationalError

from zhanor_admin.models.admin_user import AdminUser
from zhanor_admin.models.admin_group import AdminGroup
from zhanor_admin.models.admin_rule import AdminRule
from zhanor_admin.models.attachment_file import AttachmentFile
from zhanor_admin.models.attachment_image import AttachmentImage
from zhanor_admin.models.general_category import GeneralCategory
from zhanor_admin.models.general_config import GeneralConfig
from zhanor_admin.models.user_group import UserGroup
from zhanor_admin.models.user_rule import UserRule
from zhanor_admin.models.user_user import UserUser



def setup_models(dbsession):

    dbsession.add(AdminGroup(id='1', pid='0', name='admin', rules='*', createtime='2024-04-05 12:15:11', updatetime='2024-04-05 12:15:11', status='normal'))
    dbsession.add(AdminGroup(id='2', pid='2', name='editor', rules='1,2', createtime='2024-04-05 12:15:38', updatetime='2024-04-05 13:59:18', status='normal'))
    dbsession.add(AdminRule(id='1', type='menu', pid='0', addon='0', name='admin.dashboard', url_path='/admin/dashboard', title='Dashboard', description='None', icon='ti ti-dashboard', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='1', status='normal'))
    dbsession.add(AdminRule(id='2', type='menu', pid='0', addon='0', name='admin.generals', url_path='/admin/generals', title='Generals', description='None', icon='ti ti-settings', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='2', status='normal'))
    dbsession.add(AdminRule(id='3', type='menu', pid='2', addon='0', name='admin.general.profile', url_path='/admin/general/profile', title='Profile', description='None', icon='ti ti-user', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='11', status='normal'))
    dbsession.add(AdminRule(id='4', type='action', pid='3', addon='0', name='admin.general.profile.save', url_path='/admin/general/profile/save', title='Save', description='', icon='', menutype='blank', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='34', status='normal'))
    dbsession.add(AdminRule(id='5', type='menu', pid='2', addon='0', name='admin.general.category', url_path='/admin/general/category', title='Category', description='None', icon='ti ti-leaf', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='7', status='normal'))
    dbsession.add(AdminRule(id='6', type='action', pid='6', addon='0', name='admin.general.category.add', url_path='/admin/general/category/add', title='Add', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='27', status='normal'))
    dbsession.add(AdminRule(id='7', type='action', pid='6', addon='0', name='admin.general.category.edit', url_path='/admin/general/category/edit/{id}', title='Edit', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='28', status='normal'))
    dbsession.add(AdminRule(id='8', type='action', pid='6', addon='0', name='admin.general.category.save', url_path='/admin/general/category/save', title='Save', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='28', status='normal'))
    dbsession.add(AdminRule(id='9', type='action', pid='6', addon='0', name='admin.general.category.delete', url_path='/admin/general/category/delete', title='Delete', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='29', status='normal'))
    dbsession.add(AdminRule(id='10', type='menu', pid='2', addon='0', name='admin.general.config', url_path='/admin/general/config', title='Config', description='None', icon='ti ti-cog', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='8', status='normal'))
    dbsession.add(AdminRule(id='11', type='action', pid='10', addon='0', name='admin.general.config.add', url_path='/admin/general/config/add', title='Add', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='32', status='normal'))
    dbsession.add(AdminRule(id='12', type='action', pid='10', addon='0', name='admin.general.config.save', url_path='/admin/general/config/save', title='Save', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='33', status='normal'))
    dbsession.add(AdminRule(id='13', type='action', pid='10', addon='0', name='admin.general.config.delete', url_path='/admin/general/config/delete', title='Delete', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='34', status='normal'))
    dbsession.add(AdminRule(id='14', type='action', pid='10', addon='0', name='admin.general.config.table.list', url_path='/admin/general/config/table/list', title='Table List', description='None', icon='None', menutype='None', extend='None', createtime='2024-04-02 11:51:00', updatetime='2024-04-02 11:51:00', weigh='0', status='normal'))
    dbsession.add(AdminRule(id='15', type='menu', pid='0', addon='0', name='admin.attachment', url_path='/admin/attachment/', title='Attachment', description='None', icon='ti ti-paperclip', menutype='blank', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='9', status='normal'))
    dbsession.add(AdminRule(id='16', type='menu', pid='15', addon='0', name='admin.attachment.image', url_path='/admin/attachment/image', title='Attachment Image', description='None', icon='ti ti-file-image-o', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='9', status='normal'))
    dbsession.add(AdminRule(id='17', type='action', pid='16', addon='0', name='admin.attachment.image.add', url_path='/admin/attachment/image/add', title='Add', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='35', status='normal'))
    dbsession.add(AdminRule(id='18', type='action', pid='16', addon='0', name='admin.attachment.image.edit', url_path='/admin/attachment/image/edit/{id}', title='Edit', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='36', status='normal'))
    dbsession.add(AdminRule(id='19', type='action', pid='16', addon='0', name='admin.attachment.image.save', url_path='/admin/attachment/image/save', title='Save', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-23 14:32:00', updatetime='2024-01-23 14:32:00', weigh='37', status='normal'))
    dbsession.add(AdminRule(id='20', type='action', pid='16', addon='0', name='admin.attachment.image.delete', url_path='/admin/attachment/image/delete', title='Delete', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='37', status='normal'))
    dbsession.add(AdminRule(id='21', type='menu', pid='15', addon='0', name='admin.attachment.file', url_path='/admin/attachment/file', title='Attachment File', description='None', icon='ti ti-file-image-o', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='10', status='normal'))
    dbsession.add(AdminRule(id='22', type='action', pid='21', addon='0', name='admin.attachment.file.add', url_path='/admin/attachment/file/add', title='Add', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='38', status='normal'))
    dbsession.add(AdminRule(id='23', type='action', pid='21', addon='0', name='admin.attachment.file.edit', url_path='/admin/attachment/file/edit/{id}', title='Edit', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='39', status='normal'))
    dbsession.add(AdminRule(id='24', type='action', pid='21', addon='0', name='admin.attachment.file.save', url_path='/admin/attachment/file/save', title='Save', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-23 14:32:00', updatetime='2024-01-23 14:32:00', weigh='40', status='normal'))
    dbsession.add(AdminRule(id='25', type='action', pid='21', addon='0', name='admin.attachment.file.delete', url_path='/admin/attachment/file/delete', title='Delete', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='40', status='normal'))
    dbsession.add(AdminRule(id='26', type='menu', pid='0', addon='0', name='admin.addon', url_path='/admin/addon', title='Addon', description='Addon Marketplace', icon='ti ti-rocket', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='3', status='normal'))
    dbsession.add(AdminRule(id='27', type='action', pid='26', addon='0', name='admin.addon.state', url_path='/admin/addon/state', title='Update state', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='16', status='normal'))
    dbsession.add(AdminRule(id='28', type='action', pid='26', addon='0', name='admin.addon.config', url_path='/admin/addon/config', title='Setting', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='17', status='normal'))
    dbsession.add(AdminRule(id='29', type='action', pid='26', addon='0', name='admin.addon.refresh', url_path='/admin/addon/refresh', title='Refresh', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='18', status='normal'))
    dbsession.add(AdminRule(id='30', type='action', pid='26', addon='0', name='admin.addon.multi', url_path='/admin/addon/multi', title='Multi', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='19', status='normal'))
    dbsession.add(AdminRule(id='31', type='action', pid='26', addon='0', name='admin.addon.install', url_path='/admin/addon/install', title='Install', description='', icon='', menutype='blank', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='16', status='normal'))
    dbsession.add(AdminRule(id='32', type='action', pid='26', addon='0', name='admin.addon.uninstall', url_path='/admin/addon/uninstall', title='Uninstall', description='', icon='', menutype='blank', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='16', status='normal'))
    dbsession.add(AdminRule(id='33', type='action', pid='26', addon='0', name='admin.addon.update.status', url_path='/admin/addon/update/status', title='Update status', description='', icon='', menutype='blank', extend='None', createtime='2024-03-08 09:00:00', updatetime='2024-03-08 09:00:00', weigh='0', status='normal'))
    dbsession.add(AdminRule(id='34', type='action', pid='26', addon='0', name='admin.addon.download', url_path='/admin/addon/download', title='Download', description='', icon='', menutype='blank', extend='None', createtime='2024-03-14 09:18:00', updatetime='2024-03-14 09:18:00', weigh='0', status='normal'))
    dbsession.add(AdminRule(id='35', type='menu', pid='0', addon='0', name='admin.auth', url_path='/auth', title='Auth', description='None', icon='ti ti-adjustments-alt', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='4', status='normal'))
    dbsession.add(AdminRule(id='36', type='menu', pid='35', addon='0', name='admin.admin.user', url_path='/admin/admin/user', title='Admin Manage', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='20', status='normal'))
    dbsession.add(AdminRule(id='37', type='action', pid='37', addon='0', name='admin.admin.user.add', url_path='/admin/admin/user/add', title='Add', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='41', status='normal'))
    dbsession.add(AdminRule(id='38', type='action', pid='37', addon='0', name='admin.admin.user.edit', url_path='/admin/admin/user/edit/{id}', title='Edit', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='42', status='normal'))
    dbsession.add(AdminRule(id='39', type='action', pid='37', addon='0', name='admin.admin.user.save', url_path='/admin/admin/user/save', title='Save', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-23 14:32:00', updatetime='2024-01-23 14:32:00', weigh='43', status='normal'))
    dbsession.add(AdminRule(id='40', type='action', pid='37', addon='0', name='admin.admin.user.delete', url_path='/admin/admin/user/delete', title='Delete', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='43', status='normal'))
    dbsession.add(AdminRule(id='41', type='menu', pid='35', addon='0', name='admin.admin.group', url_path='/admin/admin/group', title='Admin Group', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='21', status='normal'))
    dbsession.add(AdminRule(id='42', type='action', pid='41', addon='0', name='admin.admin.group.add', url_path='/admin/admin/group/add', title='Add', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='44', status='normal'))
    dbsession.add(AdminRule(id='43', type='action', pid='41', addon='0', name='admin.admin.group.edit', url_path='/admin/admin/group/edit/{id}', title='Edit', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='45', status='normal'))
    dbsession.add(AdminRule(id='44', type='action', pid='41', addon='0', name='admin.admin.group.save', url_path='/admin/admin/group/save', title='Save', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-23 14:32:00', updatetime='2024-01-23 14:32:00', weigh='46', status='normal'))
    dbsession.add(AdminRule(id='45', type='action', pid='41', addon='0', name='admin.admin.group.delete', url_path='/admin/admin/group/delete', title='Delete', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='46', status='normal'))
    dbsession.add(AdminRule(id='46', type='menu', pid='35', addon='0', name='admin.admin.rule', url_path='/admin/admin/rule', title='Admin Rule', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='47', status='normal'))
    dbsession.add(AdminRule(id='47', type='action', pid='47', addon='0', name='admin.admin.rule.add', url_path='/admin/admin/rule/add', title='Add', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='47', status='normal'))
    dbsession.add(AdminRule(id='48', type='action', pid='47', addon='0', name='admin.admin.rule.edit', url_path='/admin/admin/rule/edit/{id}', title='Edit', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='48', status='normal'))
    dbsession.add(AdminRule(id='49', type='action', pid='47', addon='0', name='admin.admin.rule.save', url_path='/admin/admin/rule/save', title='Save', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-23 14:32:00', updatetime='2024-01-23 14:32:00', weigh='49', status='normal'))
    dbsession.add(AdminRule(id='50', type='action', pid='47', addon='0', name='admin.admin.rule.delete', url_path='/admin/admin/rule/delete', title='Delete', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='49', status='normal'))
    dbsession.add(AdminRule(id='51', type='menu', pid='35', addon='0', name='admin.admin.log', url_path='/admin/admin/log', title='Admin Log', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='50', status='normal'))
    dbsession.add(AdminRule(id='52', type='action', pid='51', addon='0', name='admin.admin.log.delete', url_path='/admin/admin/log/delete', title='Delete', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='51', status='normal'))
    dbsession.add(AdminRule(id='53', type='menu', pid='0', addon='0', name='admin.users', url_path='/admin/users', title='User Manage', description='None', icon='ti ti-user', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='24', status='normal'))
    dbsession.add(AdminRule(id='54', type='menu', pid='53', addon='0', name='admin.user.user', url_path='/admin/user/user', title='User Manage', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='24', status='normal'))
    dbsession.add(AdminRule(id='55', type='action', pid='54', addon='0', name='admin.user.user.add', url_path='/admin/user/user/add', title='Add', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='54', status='normal'))
    dbsession.add(AdminRule(id='56', type='action', pid='54', addon='0', name='admin.user.user.edit', url_path='/admin/user/user/edit/{id}', title='Edit', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='53', status='normal'))
    dbsession.add(AdminRule(id='57', type='action', pid='54', addon='0', name='admin.user.user.save', url_path='/admin/user/user/save', title='Save', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-23 14:32:00', updatetime='2024-01-23 14:32:00', weigh='55', status='normal'))
    dbsession.add(AdminRule(id='58', type='action', pid='54', addon='0', name='admin.user.user.delete', url_path='/admin/user/user/delete', title='Del', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='55', status='normal'))
    dbsession.add(AdminRule(id='59', type='menu', pid='53', addon='0', name='admin.user.group', url_path='/admin/user/group', title='User Group', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='25', status='normal'))
    dbsession.add(AdminRule(id='60', type='action', pid='59', addon='0', name='admin.user.group.add', url_path='/admin/user/group/add', title='Add', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='56', status='normal'))
    dbsession.add(AdminRule(id='61', type='action', pid='59', addon='0', name='admin.user.group.edit', url_path='/admin/user/group/edit/{id}', title='Edit', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='57', status='normal'))
    dbsession.add(AdminRule(id='62', type='action', pid='59', addon='0', name='admin.user.group.save', url_path='/admin/user/group/save', title='Save', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-23 14:32:00', updatetime='2024-01-23 14:32:00', weigh='58', status='normal'))
    dbsession.add(AdminRule(id='63', type='action', pid='59', addon='0', name='admin.user.group.delete', url_path='/admin/user/group/delete', title='Del', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='58', status='normal'))
    dbsession.add(AdminRule(id='64', type='menu', pid='53', addon='0', name='admin.user.rule', url_path='/admin/user/rule', title='User Rule', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='26', status='normal'))
    dbsession.add(AdminRule(id='65', type='action', pid='65', addon='0', name='admin.user.rule.add', url_path='/admin/user/rule/add', title='Add', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='61', status='normal'))
    dbsession.add(AdminRule(id='66', type='action', pid='65', addon='0', name='admin.user.rule.edit', url_path='/admin/user/rule/edit/{id}', title='Edit', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='62', status='normal'))
    dbsession.add(AdminRule(id='67', type='action', pid='65', addon='0', name='admin.user.rule.save', url_path='/admin/user/rule/save', title='Save', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-23 14:32:00', updatetime='2024-01-23 14:32:00', weigh='63', status='normal'))
    dbsession.add(AdminRule(id='68', type='action', pid='65', addon='0', name='admin.user.rule.delete', url_path='/admin/user/rule/delete', title='Del', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='60', status='normal'))
    dbsession.add(AdminRule(id='69', type='menu', pid='53', addon='0', name='admin.user.balance.log', url_path='/admin/user/balance/log', title='User Balance Log', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='25', status='normal'))
    dbsession.add(AdminRule(id='70', type='action', pid='69', addon='0', name='admin.user.balance.log.delete', url_path='/admin/user/balance/log/delete', title='Del', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='58', status='normal'))
    dbsession.add(AdminRule(id='71', type='menu', pid='53', addon='0', name='admin.user.score.log', url_path='/admin/user/score/log', title='User Score Log', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='25', status='normal'))
    dbsession.add(AdminRule(id='72', type='action', pid='71', addon='0', name='admin.user.score.log.delete', url_path='/admin/user/score/log/delete', title='Del', description='None', icon='None', menutype='addtabs', extend='None', createtime='2024-01-22 14:32:00', updatetime='2024-01-22 14:32:00', weigh='58', status='normal'))
    dbsession.add(AdminUser(id='1', group_id='1', name='admin', nickname='Admin8888', password='$2b$12$FD9oSjeZ6McgfXWHvpfGHuj34SLy9kqciSwa0o8fp4k90AGCltddK', avatar='/assets/img/avatar.png', email='admin@admin.com', mobile='', loginfailure='0', logintime='2024-03-05 01:34:35', loginip='27.30.110.110', createtime='2024-03-05 02:32:30', updatetime='2024-04-05 11:43:36', token='', status='normal'))
    dbsession.add(AdminUser(id='2', group_id='1', name='linjia', nickname='linjia', password='$2b$12$fFIQqrjla98AyWWFqH9VH.QiJJ5Eckvu4vzBej0oizXG5m.qhxKQ6', avatar='/assets/img/avatar.png	', email='linjia@foxmail.com', mobile='18811118888', loginfailure='0', logintime='2024-04-05 12:15:48', loginip='', createtime='2024-04-05 12:16:27', updatetime='2024-04-05 12:18:16', token='', status='normal'))
    dbsession.add(AttachmentFile(id='1', category='upload', admin_id='0', user_id='0', path_file='/static/uploads/20240416/f3f7aa40-3d82-49e4-b5fb-257c36d28207.docx', file_name='数据安全管理制度.docx', file_size='12464', mimetype='', extparam='None', createtime='2024-04-16 11:17:47', updatetime='2024-04-16 11:17:47', storage='', sha1='', general_attachmentcol=''))
    dbsession.add(AttachmentImage(id='1', category='upload', admin_id='0', user_id='0', path_image='/static/uploads/20240416/4592186f-e542-446d-8c94-3162fcea7f9b.png', image_width='512', image_height='512', image_type='webp', name='著名画家.png', file_size='440344', mimetype='image/webp', extparam='None', createtime='2024-04-16 11:17:24', updatetime='None', storage='', sha1='', general_attachmentcol=''))
    dbsession.add(AttachmentImage(id='2', category='upload', admin_id='0', user_id='0', path_image='/static/uploads/20240416/5a67467a-3837-41ba-b8ff-aab1dd21c8c2.png', image_width='512', image_height='512', image_type='webp', name='爱因斯坦.png', file_size='445480', mimetype='image/webp', extparam='None', createtime='2024-04-16 11:17:34', updatetime='None', storage='', sha1='', general_attachmentcol=''))
    dbsession.add(AttachmentImage(id='3', category='upload', admin_id='0', user_id='0', path_image='/static/uploads/20240416/2ffa4032-c75b-455d-9e51-6d26018824cc.png', image_width='512', image_height='512', image_type='webp', name='珍珠耳环的女孩.png', file_size='499674', mimetype='image/webp', extparam='None', createtime='2024-04-16 11:17:34', updatetime='None', storage='', sha1='', general_attachmentcol=''))
    dbsession.add(GeneralCategory(id='1', pid='1', type='default', name='default', image='', keywords='', description='', createtime='2024-03-28 14:10:34', updatetime='2024-03-28 14:10:34', weigh='1', status='normal'))
    dbsession.add(GeneralConfig(id='1', name='name', group='basic', title='Site name', tip='Please Input  Site name', type='string', visible='', value='栈鱼后台管理系统1.0', content='', rule='required', extend='', setting=''))
    dbsession.add(GeneralConfig(id='2', name='copyright', group='basic', title='Copyright', tip='Please Input  Copyright', type='string', visible='', value='Copyright &copy; 2024 <a href="https://admin-panel.zhanor.com" class="link-secondary">栈鱼后台管理系统 1.0</a>. All rights reserved.', content='', rule='', extend='', setting=''))
    dbsession.add(GeneralConfig(id='3', name='cdnurl', group='basic', title='Cdn url', tip='Please Input  Site name', type='string', visible='', value='https://zhanor.com', content='', rule='', extend='', setting=''))
    dbsession.add(GeneralConfig(id='4', name='version', group='basic', title='Version', tip='Please Input  Version', type='string', visible='', value='1.0.1', content='', rule='required', extend='', setting=''))
    dbsession.add(GeneralConfig(id='5', name='timezone', group='basic', title='Timezone', tip='', type='string', visible='', value='Asia/Shanghai', content='', rule='required', extend='', setting=''))
    dbsession.add(GeneralConfig(id='6', name='forbiddenip', group='basic', title='Forbidden ip', tip='Please Input  Forbidden ip', type='text', visible='', value='12.23.21.1  1.2.3.6', content='', rule='', extend='', setting=''))
    dbsession.add(GeneralConfig(id='7', name='languages', group='basic', title='Languages', tip='', type='array', visible='', value='{"backend": "zh-cn", "frontend": "zh-cn"}', content='', rule='required', extend='', setting=''))
    dbsession.add(GeneralConfig(id='8', name='fixedpage', group='basic', title='Fixed page', tip='Please Input Fixed page', type='string', visible='', value='dashboard', content='', rule='required', extend='', setting=''))
    dbsession.add(GeneralConfig(id='9', name='categorytype', group='dictionary', title='Category type', tip='', type='array', visible='', value='{"default": "Default", "page": "Page", "article": "Article"}', content='', rule='', extend='', setting=''))
    dbsession.add(GeneralConfig(id='11', name='mail_type', group='email', title='Mail type', tip='Please Input Mail type', type='select', visible='', value='0', content='["Please Select","SMTP"]', rule='', extend='', setting=''))
    dbsession.add(GeneralConfig(id='12', name='mail_smtp_host', group='email', title='Mail smtp host', tip='Please Input Mail smtp host', type='string', visible='', value='smtp.qq.com', content='', rule='', extend='', setting=''))
    dbsession.add(GeneralConfig(id='13', name='mail_smtp_port', group='email', title='Mail smtp port', tip='Please Input  Mail smtp port(default25,SSL：465,TLS：587)', type='string', visible='', value='465', content='', rule='', extend='', setting=''))
    dbsession.add(GeneralConfig(id='14', name='mail_smtp_user', group='email', title='Mail smtp user', tip='Please Input Mail smtp user', type='string', visible='', value='10000', content='', rule='', extend='', setting=''))
    dbsession.add(GeneralConfig(id='15', name='mail_smtp_pass', group='email', title='Mail smtp password', tip='Please Input  Mail smtp password', type='string', visible='', value='password', content='', rule='', extend='', setting=''))
    dbsession.add(GeneralConfig(id='16', name='mail_verify_type', group='email', title='Mail vertify type', tip='Please Input Mail vertify type', type='select', visible='', value='0', content='["None","TLS","SSL"]', rule='', extend='', setting=''))
    dbsession.add(GeneralConfig(id='17', name='mail_from', group='email', title='Mail from', tip='', type='string', visible='', value='10000@qq.com', content='', rule='', extend='', setting=''))
    dbsession.add(GeneralConfig(id='18', name='image_category', group='dictionary', title='Attachment Image category', tip='', type='array', visible='', value='{"default": "Default", "upload": "Upload"}', content='', rule='', extend='', setting=''))
    dbsession.add(GeneralConfig(id='19', name='file_category', group='dictionary', title='Attachment File category', tip='', type='array', visible='', value='{"default": "Default", "upload": "Upload"}', content='', rule='', extend='', setting=''))
    dbsession.add(GeneralConfig(id='23', name='user_page_title', group='user', title='User Page Title', tip='User Page Title', type='text', visible='', value='Member Center', content='', rule='letters', extend='', setting=''))
    dbsession.add(GeneralConfig(id='24', name='user_footer', group='user', title='User Center Footer', tip='User Center Footer', type='string', visible='', value='Copyright &copy; 2024 <a href="https://admin-panel.zhanor.com" class="link-secondary">会员中心</a>. All rights reserved.', content='', rule='required', extend='', setting=''))
    dbsession.add(UserGroup(id='1', name='default', rules='1,2', createtime='2024-03-27 07:37:07', updatetime='2024-03-27 07:37:07', status='normal'))
    dbsession.add(UserGroup(id='3', name='vip1', rules='1,2', createtime='2024-03-27 15:40:57', updatetime='2024-03-27 15:40:57', status='normal'))
    dbsession.add(UserRule(id='1', pid='0', type='menu', name='user.dashboard', url_path='/user/dashboard', title='User Dashboard', icon='ti ti-hexagonal-prism', description='User Dashboard', createtime='2024-04-01 09:53:30', updatetime='2024-04-01 15:19:07', weigh='1', status='normal'))
    dbsession.add(UserRule(id='2', pid='0', type='menu', name='user.profile', url_path='/user/profile', title='Profile', icon='ti ti-alert-square-rounded', description='', createtime='2024-04-01 10:08:49', updatetime='2024-04-01 12:50:48', weigh='0', status='normal'))
    dbsession.add(UserRule(id='3', pid='0', type='menu', name='user.balance.log', url_path='/user/balance/log', title='Balance Log', icon='ti ti-color-swatch', description='', createtime='2024-04-01 10:09:32', updatetime='2024-04-01 13:11:04', weigh='0', status='normal'))
    dbsession.add(UserRule(id='4', pid='0', type='menu', name='user.score.log', url_path='/user/score/log', title='Score Log', icon='ti ti-align-right', description='', createtime='2024-04-01 10:10:03', updatetime='2024-04-01 13:17:28', weigh='0', status='normal'))
    dbsession.add(UserRule(id='5', pid='0', type='action', name='user.logout', url_path='/user/logout', title='Logout', icon='ti ti-location-share', description='', createtime='2024-04-01 10:11:22', updatetime='2024-04-01 13:17:42', weigh='0', status='normal'))
    dbsession.add(UserRule(id='6', pid='2', type='action', name='user.profile.save', url_path='/user/profile/save', title='Profile Save', icon='', description='', createtime='2024-04-01 10:21:23', updatetime='2024-04-01 10:21:23', weigh='0', status='normal'))
    dbsession.add(UserUser(id='1', user_group_id='1', name='user1', nickname='user1', password='$2b$12$Qh2TzcECJH80i.xD/72vZO2zibNJviV4eTJ4HDT7lXK9MJlqWdpFy', email='user1@user.com', mobile='18811118888', avatar='static/img/avator.png', level='0', gender='male', birthday='None', bio='', balance='0', score='0', successions='1', maxsuccessions='1', prevtime='2024-04-16 10:22:07', logintime='2024-04-16 10:43:52', loginip='127.0.0.1', loginfailure='1', joinip='127.0.0.1', createtime='2024-04-16 10:22:07', updatetime='2024-04-16 10:22:07', verification='0', token='', status='normal'))


def parse_args(argv):
    parser = argparse.ArgumentParser()
    parser.add_argument(
        'config_uri',
        help='Configuration file, e.g., development.ini',
    )
    return parser.parse_args(argv[1:])


def main(argv=sys.argv):
    args = parse_args(argv)
    setup_logging(args.config_uri)
    env = bootstrap(args.config_uri)

    try:
        with env['request'].tm:
            dbsession = env['request'].dbsession
            setup_models(dbsession)
    except OperationalError:
        print('''Error''')
